server:
  port: 8899
  servlet.context-path: /bookstore

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:E:\2023秋季学期文件\实验课代码\Class1-4\back\src\main\resources\static\bookstore.db
    username: root
    password: root
  devtools.restart.enabled: true
  devtools.restart.additional-paths: src/main/java
  devtools.restart.poll-interval: 2s
  devtools.restart.quiet-period: 1s
  freemarker.cache: false
  mvc.pathmatch.matching-strategy: ANT_PATH_MATCHER
logging:
  level:
    com.example.*: debug